# Generated by Django 5.0.2 on 2024-02-10 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='fullname',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
