# Generated by Django 5.0.2 on 2024-02-10 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0002_client_fullname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='fullname',
        ),
        migrations.RemoveField(
            model_name='client',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='date',
            name='place',
            field=models.IntegerField(null=True),
        ),
    ]
