# Generated by Django 5.0.2 on 2024-02-11 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0003_remove_client_fullname_remove_client_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
