# Generated by Django 5.0.2 on 2024-02-11 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0004_service_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='Profile_pic',
            field=models.ImageField(default='images/default/DefaultPic.png', upload_to='images/Uploaded/Pfp/'),
        ),
    ]
