# Generated by Django 5.0.2 on 2024-02-12 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0005_alter_client_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='date',
            name='client',
        ),
        migrations.RemoveField(
            model_name='date',
            name='service',
        ),
        migrations.AddField(
            model_name='date',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Base.client'),
        ),
        migrations.AddField(
            model_name='date',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Base.service'),
        ),
    ]
