# Generated by Django 5.0.2 on 2024-02-13 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0006_remove_date_client_remove_date_service_date_client_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='Qte',
            field=models.IntegerField(default=0),
        ),
    ]
