# Generated by Django 5.0.2 on 2024-04-23 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0010_service_average_time_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='date',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='service',
            name='profile_pic',
            field=models.ImageField(default='Default_pfp.jpg', null=True, upload_to='service_pfp/'),
        ),
    ]
