# Generated by Django 5.0.2 on 2024-04-28 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0011_date_is_completed_service_profile_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('place', models.IntegerField(null=True)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Base.client')),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Base.service')),
            ],
        ),
    ]
