# Generated by Django 5.0.2 on 2024-04-28 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0012_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='history',
            name='is_completed',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='history',
            name='place',
            field=models.IntegerField(),
        ),
    ]
