# Generated by Django 5.0.2 on 2024-04-28 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0013_alter_history_date_alter_history_is_completed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='place',
        ),
    ]
