# Generated by Django 5.0.2 on 2024-05-01 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0014_remove_history_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='Expired_Token',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='Expired_Token',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
