# Generated by Django 5.0.2 on 2024-05-03 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0015_client_expired_token_service_expired_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='Expired_Token',
        ),
        migrations.RemoveField(
            model_name='service',
            name='Expired_Token',
        ),
    ]
